### ISSUE TITLE
You can only create one shader.

### ISSUE THREAD

**Issue by AnastasiaDunbar** [glslio/transitions.glsl.io#94]
Making a new one will just replace the old one.

**Comment by gre** [comment]
I'm aware of this, that's an annoying bug because it is a consequence of a recent change in the new Gist API: **it no longer allows to Fork a gist more than once** like it **accidentally** used to allow.
It breaks our architecture idea and requires a fundamental change in the way it works (can no longer requires on listing the forks to just list the transitions) and I'm not sure I can find the time to fix it.
I really liked that we had so far NO DATA on our server and that everything is community driven 100% via forking a gist.

I've contacted the Github/Gist team, to report this and request to have this feature back, but it does not seem to be a priority for them, anyway maybe worth asking them again if you want.

**Comment by gre** [comment]
closing this. please see https://github.com/glslio/transitions.glsl.io/issues/100

**Comment by gre** [comment]
@AnastasiaDunbar please see https://github.com/gltransitions/gl-transitions/issues/33 :) finally fixed the state of this, no longer using gist :)
