### ISSUE TITLE
Site is down

### ISSUE THREAD

**Issue by VelocityRa** [glslio/transitions.glsl.io#99]
Getting "DNS address could not be found"/`ERR_NAME_NOT_RESOLVED` error on the entire **http://glsl.io/** domain.

**Comment by gre** [comment]
sorry for that but yeah, i'm taking it down. The website was actually broken by Gist API recent changes, they don't seem to have plan fixing it, and also I don't have many time to work on that anymore. Feel free to run it yourself, you can also access all the data because it's all gists.

see also https://twitter.com/greweb/status/828649367699648515

**Comment by gre** [comment]
can you guys see https://github.com/glslio/transitions.glsl.io/issues/100 . this might be a way to reborn this idea! thanks

**Comment by AnastasiaDunbar** [comment]
RIP **glsl.io**.

**Comment by gre** [comment]
new website: https://gl-transitions.com/

**Comment by VelocityRa** [comment]
That's great!
